[package]
name = "lagon-runtime-v8-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
v8 = "0.71.2"
anyhow = "1.0.71"
hyper = { version = "0.14.26" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
httpstatus = "0.1"
